version: "3"

services:
  prometheus-nodeexporter:
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    container_name: stats-prometheus-nodeexporter
    # image: quay.io/prometheus/busybox-linux-amd64
    build: ./prometheus/arm
    networks:
      - stats
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
