version: '3'

services:
  statsd-exporter:
    command: --statsd.mapping-config=/tmp/statsd_mapping.yml --log.level="debug" --log.format="logger:stdout?json=true"
    container_name: statsd-statsd-prometheus-exporter
    depends_on:
      - prometheus
      - graphite
    image: prom/statsd-exporter
    networks:
      - stats
    ports:
      - 9102:9102
      - 9125:9125
      - 9125:9125/udp
    restart: unless-stopped
    volumes: 
      - ./statsd/statsd_mapping.yml:/tmp/statsd_mapping.yml
