version: '3'

services:
  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    container_name: stats-prometheus
    image: prom/prometheus:v2.12.0
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - stats
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus

  prometheus-alertmanager:
    container_name: stats-prometheus-alertmanager
    image: prom/alertmanager:v0.19.0
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      - stats
    ports:
      - 9093:9093
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  prometheus-pushgateway:
    container_name: stats-prometheus-pushgateway
    image: prom/pushgateway
    networks:
      - stats
    ports:
      - 9091:9091
    restart: unless-stopped


volumes:
    prometheus_data: {}